create table addresses (latitude decimal(10,7), longitude decimal(10,7), city_id bigint not null, created_at datetime(6) not null, deleted_at datetime(6), delivery_area_id bigint not null, id bigint not null auto_increment, updated_at datetime(6), user_id bigint not null, address_line varchar(255) not null, label varchar(255), phone varchar(255), postal_code varchar(255), recipient_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table auth_codes (attempts integer not null, created_at datetime(6) not null, expires_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), used_at datetime(6), user_id bigint not null, code_hash varchar(255) not null, purpose enum ('PASSWORD_RESET') not null, primary key (id)) engine=InnoDB;
create table cart_item_options (option_price decimal(10,2) not null, cart_item_id bigint not null, created_at datetime(6) not null, dish_option_id bigint not null, id bigint not null auto_increment, updated_at datetime(6), option_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table cart_items (quantity integer not null, subtotal decimal(10,2) not null, unit_price decimal(10,2) not null, cart_id bigint not null, created_at datetime(6) not null, dish_id bigint not null, id bigint not null auto_increment, updated_at datetime(6), primary key (id)) engine=InnoDB;
create table carts (created_at datetime(6) not null, expires_at datetime(6), id bigint not null auto_increment, restaurant_id bigint not null, updated_at datetime(6), user_id bigint not null, status enum ('ACTIVE','EXPIRED') not null, primary key (id)) engine=InnoDB;
create table categories (priority integer, created_at datetime(6) not null, deleted_at datetime(6), id bigint not null auto_increment, restaurant_id bigint not null, updated_at datetime(6), description varchar(255), image_url varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table cities (created_at datetime(6) not null, deleted_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table delivery_area (city_id bigint not null, created_at datetime(6) not null, deleted_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table delivery_assignments (accepted_at datetime(6), assigned_at datetime(6), created_at datetime(6) not null, delivered_at datetime(6), id bigint not null auto_increment, order_id bigint not null, picked_up_at datetime(6), rider_id bigint not null, updated_at datetime(6), status enum ('ACCEPTED','ASSIGNED','CANCELLED','DELIVERED','PICKED_UP') not null, primary key (id)) engine=InnoDB;
create table dish_option_groups (max_selections integer, min_selections integer, required bit not null, sort_order integer, created_at datetime(6) not null, deleted_at datetime(6), dish_id bigint not null, id bigint not null auto_increment, updated_at datetime(6), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table dish_options (additional_price decimal(10,2) not null, sort_order integer, created_at datetime(6) not null, deleted_at datetime(6), id bigint not null auto_increment, option_group_id bigint not null, updated_at datetime(6), name varchar(255) not null, status enum ('AVAILABLE','UNAVAILABLE') not null, primary key (id)) engine=InnoDB;
create table dishes (price decimal(10,2) not null, sort_order integer, category_id bigint not null, created_at datetime(6) not null, deleted_at datetime(6), id bigint not null auto_increment, restaurant_id bigint not null, updated_at datetime(6), description varchar(255), image_url varchar(255), name varchar(255) not null, status enum ('AVAILABLE','ON_HOLD') not null, primary key (id)) engine=InnoDB;
create table favorite_restaurants (created_at datetime(6) not null, deleted_at datetime(6), id bigint not null auto_increment, restaurant_id bigint not null, updated_at datetime(6), user_id bigint not null, primary key (id)) engine=InnoDB;
create table notifications (is_read bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), user_id bigint not null, message varchar(255) not null, title varchar(255) not null, type enum ('NEW_ORDER','ORDER_STATUS_CHANGED','SYSTEM') not null, primary key (id)) engine=InnoDB;
create table order_item_options (option_price decimal(10,2) not null, created_at datetime(6) not null, dish_option_id bigint not null, id bigint not null auto_increment, order_item_id bigint not null, updated_at datetime(6), option_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table order_items (quantity integer not null, subtotal decimal(10,2) not null, unit_price decimal(10,2) not null, created_at datetime(6) not null, dish_id bigint not null, id bigint not null auto_increment, order_id bigint not null, updated_at datetime(6), dish_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table order_status_history (changed_by_user_id bigint not null, created_at datetime(6) not null, id bigint not null auto_increment, order_id bigint not null, updated_at datetime(6), reason varchar(255), status enum ('ACCEPTED','COMPLETED','DECLINED','IN_PREPARATION','PENDING') not null, primary key (id)) engine=InnoDB;
create table orders (delivery_fee decimal(10,2) not null, estimated_cooking_minutes integer, subtotal decimal(10,2) not null, total_amount decimal(10,2) not null, accepted_at datetime(6), address_id bigint not null, cancelled_at datetime(6), created_at datetime(6) not null, delivered_at datetime(6), id bigint not null auto_increment, picked_up_at datetime(6), ready_at datetime(6), rejected_at datetime(6), restaurant_id bigint not null, updated_at datetime(6), user_id bigint not null, currency varchar(255) not null, delivery_note varchar(255), order_number varchar(255) not null, rejection_reason varchar(255), payment_method enum ('BANK_TRANSFER','CARD','CASH') not null, payment_status enum ('FAILED','PAID','PENDING','REFUNDED') not null, status enum ('ACCEPTED','COMPLETED','DECLINED','IN_PREPARATION','PENDING') not null, primary key (id)) engine=InnoDB;
create table ratings (score integer not null, created_at datetime(6) not null, dish_id bigint not null, id bigint not null auto_increment, order_id bigint not null, restaurant_id bigint not null, updated_at datetime(6), user_id bigint not null, comment varchar(255), primary key (id)) engine=InnoDB;
create table refresh_tokens (expiry_date datetime(6) not null, id bigint not null auto_increment, user_id bigint, version bigint not null, token varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurant (latitude decimal(10,7), longitude decimal(10,7), minimum_order_amount decimal(10,2), city_id bigint not null, created_at datetime(6) not null, deleted_at datetime(6), id bigint not null auto_increment, owner_id bigint not null, type_id bigint not null, updated_at datetime(6), address varchar(255), description varchar(255), logo_url varchar(255), name varchar(255) not null, phone varchar(255), status enum ('CLOSED','OPEN') not null, primary key (id)) engine=InnoDB;
create table restaurant_delivery_areas (created_at datetime(6) not null, deleted_at datetime(6), delivery_area_id bigint not null, id bigint not null auto_increment, restaurant_id bigint not null, updated_at datetime(6), primary key (id)) engine=InnoDB;
create table restaurant_types (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), description varchar(255), name varchar(255) not null, primary key (id)) engine=InnoDB;
create table restaurant_working_hours (close_time time(0), is_day_off bit not null, open_time time(0), created_at datetime(6) not null, id bigint not null auto_increment, restaurant_id bigint not null, updated_at datetime(6), day_of_week enum ('FRIDAY','MONDAY','SATURDAY','SUNDAY','THURSDAY','TUESDAY','WEDNESDAY') not null, primary key (id)) engine=InnoDB;
create table rider_profiles (availability bit not null, created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), user_id bigint not null, status enum ('ACTIVE','INACTIVE','SUSPENDED') not null, transport_type enum ('BICYCLE','CAR','MOTORCYCLE','WALK') not null, primary key (id)) engine=InnoDB;
create table users (created_at datetime(6) not null, deleted_at datetime(6), email_verified_at datetime(6), id bigint not null auto_increment, phone_verified_at datetime(6), updated_at datetime(6), phone varchar(20) not null, email varchar(255) not null, name varchar(255) not null, password_hash varchar(255) not null, role enum ('ADMIN','CUSTOMER','RESTAURANT_OWNER','RIDER') not null, status enum ('ACTIVE','INACTIVE','SUSPENDED') not null, primary key (id)) engine=InnoDB;
alter table carts add constraint UK64t7ox312pqal3p7fg9o503c2 unique (user_id);
alter table categories add constraint uk_category_restaurant_name unique (restaurant_id, name);
alter table cities add constraint UKl61tawv0e2a93es77jkyvi7qa unique (name);
alter table favorite_restaurants add constraint UKq40957j6hum81b6hn72m5hho unique (user_id, restaurant_id);
alter table orders add constraint UKnthkiu7pgmnqnu86i2jyoe2v7 unique (order_number);
alter table refresh_tokens add constraint UK7tdcd6ab5wsgoudnvj7xf1b7l unique (user_id);
alter table refresh_tokens add constraint UKghpmfn23vmxfu3spu3lfg4r2d unique (token);
alter table restaurant_delivery_areas add constraint UKpkeh7o1fkyslcqc21uc6uxaxg unique (restaurant_id, delivery_area_id);
alter table restaurant_types add constraint UK7medp73rlp36hpe0pylydar8e unique (name);
alter table rider_profiles add constraint UKn2j4l8h8kicvr6xkgjoe974br unique (user_id);
alter table addresses add constraint FK9fkb8qaj71tiyr9htkmn7r8y5 foreign key (city_id) references cities (id);
alter table addresses add constraint FK73b2finwtk4eqgnvjyo834tm6 foreign key (delivery_area_id) references delivery_area (id);
alter table addresses add constraint FK1fa36y2oqhao3wgg2rw1pi459 foreign key (user_id) references users (id);
alter table auth_codes add constraint FK4wrsuvucbpy8tvhfsg60vlmoa foreign key (user_id) references users (id);
alter table cart_item_options add constraint FKrkqjsm24carqadm4bamge81vl foreign key (cart_item_id) references cart_items (id);
alter table cart_item_options add constraint FKlrxhriwfr1j4ksamtijivj7bl foreign key (dish_option_id) references dish_options (id);
alter table cart_items add constraint FKpcttvuq4mxppo8sxggjtn5i2c foreign key (cart_id) references carts (id);
alter table cart_items add constraint FKqf96jt4hthdxw36s3ebnq1yns foreign key (dish_id) references dishes (id);
alter table carts add constraint FKjm6ynf9nm1wrfa7tjpxrwp32l foreign key (restaurant_id) references restaurant (id);
alter table carts add constraint FKb5o626f86h46m4s7ms6ginnop foreign key (user_id) references users (id);
alter table categories add constraint FK60bbnx82yt5aoymhhsimseklt foreign key (restaurant_id) references restaurant (id);
alter table delivery_area add constraint FKfcar75t39nffye792guwmfx1g foreign key (city_id) references cities (id);
alter table delivery_assignments add constraint FKal6lp5gq27djtgpdsn2907uq5 foreign key (order_id) references orders (id);
alter table delivery_assignments add constraint FKp7hgoynomv1rosk73v4ptb557 foreign key (rider_id) references rider_profiles (id);
alter table dish_option_groups add constraint FK6q0hny73ek9hlwj4qrconu3dx foreign key (dish_id) references dishes (id);
alter table dish_options add constraint FK1e6ct9wh8mt3dy0jp3i22gfjx foreign key (option_group_id) references dish_option_groups (id);
alter table dishes add constraint FKgbu6erefir17660qutbbjnma7 foreign key (category_id) references categories (id);
alter table dishes add constraint FK8hb3y72jckjfgp1fyn0rqixar foreign key (restaurant_id) references restaurant (id);
alter table favorite_restaurants add constraint FKnnmu9g6y33tomr2luyv49hb9v foreign key (restaurant_id) references restaurant (id);
alter table favorite_restaurants add constraint FKd6fa5p8rrjdlmfv4xo28ivjfv foreign key (user_id) references users (id);
alter table notifications add constraint FK9y21adhxn0ayjhfocscqox7bh foreign key (user_id) references users (id);
alter table order_item_options add constraint FKso7wu6km5y2bba9lrdi79iv3v foreign key (dish_option_id) references dish_options (id);
alter table order_item_options add constraint FKoxx4p9r1asmwop4wuynr6t0g6 foreign key (order_item_id) references order_items (id);
alter table order_items add constraint FKn06bdypik73hotpxvefsrtn77 foreign key (dish_id) references dishes (id);
alter table order_items add constraint FKbioxgbv59vetrxe0ejfubep1w foreign key (order_id) references orders (id);
alter table order_status_history add constraint FKbnuj0gvhjwxodmmu7gj3iivse foreign key (changed_by_user_id) references users (id);
alter table order_status_history add constraint FKnmcbg3mmbt8wfva97ra40nmp3 foreign key (order_id) references orders (id);
alter table orders add constraint FKhlglkvf5i60dv6dn397ethgpt foreign key (address_id) references addresses (id);
alter table orders add constraint FKi7hgjxhw21nei3xgpe4nnpenh foreign key (restaurant_id) references restaurant (id);
alter table orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users (id);
alter table ratings add constraint FKrgl02m10esvjulx3lfwlu993m foreign key (dish_id) references dishes (id);
alter table ratings add constraint FKu2smk2142p4u673g5h2w419l foreign key (order_id) references orders (id);
alter table ratings add constraint FKh7l3gje9yw8ufmte2ocedljno foreign key (restaurant_id) references restaurant (id);
alter table ratings add constraint FKb3354ee2xxvdrbyq9f42jdayd foreign key (user_id) references users (id);
alter table refresh_tokens add constraint FK1lih5y2npsf8u5o3vhdb9y0os foreign key (user_id) references users (id);
alter table restaurant add constraint FKqmc3xv4pqhjsm4q5ib49ks0og foreign key (city_id) references cities (id);
alter table restaurant add constraint FKsh6jyud453k5uisje3pyubk39 foreign key (owner_id) references users (id);
alter table restaurant add constraint FKsv63atv3j5n45w94hcc79c7m4 foreign key (type_id) references restaurant_types (id);
alter table restaurant_delivery_areas add constraint FKl7aykpywivgaayt7js2djbnlv foreign key (delivery_area_id) references delivery_area (id);
alter table restaurant_delivery_areas add constraint FKddr9uxymifn89cqjgdq819xwi foreign key (restaurant_id) references restaurant (id);
alter table restaurant_working_hours add constraint FKs8gklmy8yjc1yunusfed14v53 foreign key (restaurant_id) references restaurant (id);
alter table rider_profiles add constraint FKd9p3fxlqny81bw9v9yg6yvbec foreign key (user_id) references users (id);
