-- Add READY_FOR_PICKUP and CANCELLED to orders and order_status_history status enum columns

ALTER TABLE orders 
    MODIFY COLUMN status ENUM('PENDING', 'ACCEPTED', 'IN_PREPARATION', 'READY_FOR_PICKUP', 'DELIVERED', 'COMPLETED', 'DECLINED', 'CANCELLED') NOT NULL;

ALTER TABLE order_status_history 
    MODIFY COLUMN status ENUM('PENDING', 'ACCEPTED', 'IN_PREPARATION', 'READY_FOR_PICKUP', 'DELIVERED', 'COMPLETED', 'DECLINED', 'CANCELLED') NOT NULL;
